import { Router } from 'express';
import { RadiusItem } from '../core/types';
import { correlateItems } from '../core/correlations';
import { sanitizeRaw } from '../core/sanitize';

const router = Router();

const DEMO_DATA: RadiusItem[] = [
  // --- PROJECT: AUTH SERVICE REFACTOR (ENG-142) ---
  {
    id: 'demo-gh-1',
    source: 'github',
    entityType: 'pr',
    title: 'Failed: CI workflow run (main)',
    description: 'Production build failing on main branch due to dependency mismatch in auth-service.',
    url: 'https://github.com/demo/repo/actions/runs/1',
    severity: 'critical',
    health: 'Overdue',
    urgencyScore: 0.05,
    impactScore: 5,
    confidenceScore: 1,
    radiusScore: 95,
    category: 'engineering',
    owner: 'yugaaank',
    team: 'Platform',
    tags: ['ci-failure', 'production-blocker'],
    updatedAt: new Date(Date.now() - 1800000).toISOString(),
    correlationKeys: ['ENG-142', 'auth-service'],
    raw: {}
  },
  {
    id: 'demo-cu-1',
    source: 'clickup',
    entityType: 'task',
    title: 'Fix auth-service dependency mismatch',
    description: 'Root cause of the current CI failure on main branch. Blocks deployment.',
    url: 'https://app.clickup.com/t/ENG-142',
    severity: 'critical',
    health: 'Overdue',
    urgencyScore: 0.1,
    impactScore: 5,
    confidenceScore: 1,
    radiusScore: 98,
    category: 'engineering',
    owner: 'yugaaank',
    team: 'Platform',
    dueDate: new Date(Date.now() - 86400000).toISOString(),
    tags: ['p0', 'blocker'],
    correlationKeys: ['ENG-142', 'auth-service'],
    raw: {}
  },
  {
    id: 'demo-ops-3',
    source: 'sentry',
    entityType: 'error',
    title: 'NullPointerException in AuthMiddleware',
    description: 'Occurring for 15% of all traffic in production since last deploy.',
    url: 'https://sentry.io/issues/555',
    severity: 'high',
    health: 'critical',
    urgencyScore: 0.1,
    impactScore: 4,
    confidenceScore: 1,
    radiusScore: 92,
    category: 'engineering',
    tags: ['regression', 'auth'],
    correlationKeys: ['auth-service', 'ENG-142'],
    raw: {}
  },
  {
    id: 'demo-no-1',
    source: 'notion',
    entityType: 'doc',
    title: 'Auth Service Architecture v2',
    description: 'Technical specification for the new middleware pattern. Needs review.',
    url: 'https://notion.so/docs/auth-arch',
    severity: 'medium',
    health: 'Stale',
    urgencyScore: 70,
    impactScore: 3,
    confidenceScore: 0.7,
    radiusScore: 30,
    category: 'docs',
    updatedAt: new Date(Date.now() - 6048000000).toISOString(),
    correlationKeys: ['ENG-142', 'auth-service'],
    raw: {}
  },

  // --- PROJECT: Q3 PLANNING (RFC-22 / STRAT-44) ---
  {
    id: 'demo-no-2',
    source: 'notion',
    entityType: 'doc',
    title: '[RFC] Global Workspace Filtering',
    description: 'Proposal for the new filtering engine architecture.',
    url: 'https://notion.so/docs/rfc-22',
    severity: 'high',
    health: 'Stuck',
    urgencyScore: 1,
    impactScore: 4,
    confidenceScore: 0.9,
    radiusScore: 75,
    category: 'business',
    owner: 'yugaaank',
    tags: ['rfc', 'needs-review'],
    correlationKeys: ['RFC-22', 'STRAT-44'],
    raw: {}
  },
  {
    id: 'demo-cu-2',
    source: 'clickup',
    entityType: 'task',
    title: 'Update Q3 Roadmap Visuals',
    description: 'Finalizing the board for the stakeholder meeting.',
    url: 'https://app.clickup.com/t/STRAT-44',
    severity: 'medium',
    health: 'Stuck',
    urgencyScore: 1,
    impactScore: 3,
    confidenceScore: 0.8,
    radiusScore: 40,
    category: 'business',
    owner: 'sarah',
    tags: ['blocked', 'waiting-on-design'],
    correlationKeys: ['STRAT-44', 'RFC-22'],
    raw: {}
  },

  // --- OPS: INFRASTRUCTURE HEALTH ---
  {
    id: 'demo-ops-1',
    source: 'pagerduty',
    entityType: 'incident',
    title: 'CRITICAL: High Latency in us-east-1',
    description: 'P99 latency > 2s for all authenticated requests in Virginia region.',
    url: 'https://pagerduty.com/incidents/OPS-91',
    severity: 'critical',
    health: 'critical',
    urgencyScore: 0.01,
    impactScore: 5,
    confidenceScore: 1,
    radiusScore: 100,
    category: 'ops',
    team: 'On-Call',
    tags: ['incident', 'api'],
    updatedAt: new Date(Date.now() - 300000).toISOString(),
    correlationKeys: ['OPS-91', 'auth-service'],
    raw: {}
  },
  {
    id: 'demo-ops-2',
    source: 'datadog',
    entityType: 'alert',
    title: 'Memory Leak Detected: worker-node-04',
    description: 'Memory usage increasing linearly over 4 hours on ingest cluster.',
    url: 'https://datadoghq.com/alerts/123',
    severity: 'medium',
    health: 'warning',
    urgencyScore: 2,
    impactScore: 3,
    confidenceScore: 0.85,
    radiusScore: 55,
    category: 'ops',
    tags: ['alert', 'infrastructure'],
    correlationKeys: ['worker-04'],
    raw: {}
  },

  // --- GENERAL ENGINEERING ---
  {
    id: 'demo-gh-2',
    source: 'github',
    entityType: 'pr',
    title: 'Stale: Refactor user middleware',
    description: 'Waiting for review for 12 days. Significant changes to auth flow.',
    url: 'https://github.com/demo/repo/pull/42',
    severity: 'high',
    health: 'Stale',
    urgencyScore: 12,
    impactScore: 4,
    confidenceScore: 0.9,
    radiusScore: 65,
    category: 'engineering',
    owner: 'alice',
    tags: ['stale', 'needs-review'],
    updatedAt: new Date(Date.now() - 1036800000).toISOString(),
    correlationKeys: ['ENG-105'],
    raw: {}
  },
  {
    id: 'demo-gh-4',
    source: 'github',
    entityType: 'alert',
    title: 'Security: Vulnerable dependency (npm:lodash)',
    description: 'CVE-2024-XXXX: Prototype pollution vulnerability in lodash.',
    url: 'https://github.com/demo/repo/security/advisories/1',
    severity: 'high',
    health: 'Action Required',
    urgencyScore: 3,
    impactScore: 4,
    confidenceScore: 1,
    radiusScore: 82,
    category: 'ops',
    tags: ['security', 'dependabot'],
    correlationKeys: ['vuln-123'],
    raw: {}
  },
  {
    id: 'demo-cu-3',
    source: 'clickup',
    entityType: 'task',
    title: '[ENG-105] Fix User Middleware Tests',
    description: 'Tests failing since the refactor PR was opened.',
    url: 'https://app.clickup.com/t/ENG-105',
    severity: 'medium',
    health: 'Healthy',
    urgencyScore: 7,
    impactScore: 3,
    confidenceScore: 1,
    radiusScore: 60,
    category: 'engineering',
    owner: 'alice',
    correlationKeys: ['ENG-105'],
    raw: {}
  },

  // --- CUSTOMER & PRODUCT ---
  {
    id: 'demo-cust-1',
    source: 'intercom',
    entityType: 'message',
    title: 'VIP: Enterprise Login Issues',
    description: 'Acme Corp reporting 500 errors on SSO login page.',
    url: 'https://intercom.com/conversations/999',
    severity: 'critical',
    health: 'Action Required',
    urgencyScore: 0.2,
    impactScore: 5,
    confidenceScore: 1,
    radiusScore: 96,
    category: 'customer',
    owner: 'support-team',
    tags: ['vip', 'sso'],
    correlationKeys: ['auth-service', 'acme-corp'],
    raw: {}
  },
  {
    id: 'demo-prod-1',
    source: 'posthog',
    entityType: 'metric',
    title: 'Conversion Drop: Onboarding Flow',
    description: '15% drop in signup completion over the last 24h.',
    url: 'https://posthog.com/insights/signup-funnel',
    severity: 'high',
    health: 'warning',
    urgencyScore: 1,
    impactScore: 4,
    confidenceScore: 0.95,
    radiusScore: 78,
    category: 'product',
    tags: ['onboarding', 'conversion'],
    correlationKeys: ['onboarding-v2'],
    raw: {}
  },
  {
    id: 'demo-cu-4',
    source: 'clickup',
    entityType: 'task',
    title: 'Debug PostHog Onboarding Drop',
    description: 'Investigating the root cause of the conversion drop.',
    url: 'https://app.clickup.com/t/PROD-12',
    severity: 'high',
    health: 'Active',
    urgencyScore: 0.5,
    impactScore: 4,
    confidenceScore: 1,
    radiusScore: 85,
    category: 'product',
    owner: 'yugaaank',
    correlationKeys: ['onboarding-v2', 'PROD-12'],
    raw: {}
  },

  // --- ADDITIONAL FILLER FOR DENSITY ---
  {
    id: 'demo-f1',
    source: 'github',
    entityType: 'pr',
    title: 'Feature: New landing page',
    severity: 'low',
    health: 'Healthy',
    urgencyScore: 15,
    impactScore: 2,
    confidenceScore: 1,
    radiusScore: 20,
    category: 'engineering',
    owner: 'marketing-dev',
    raw: {},
    tags: [],
    correlationKeys: []
  },
  {
    id: 'demo-f2',
    source: 'notion',
    entityType: 'doc',
    title: 'Team Offsite Agenda',
    severity: 'low',
    health: 'Healthy',
    urgencyScore: 45,
    impactScore: 1,
    confidenceScore: 1,
    radiusScore: 5,
    category: 'tasks',
    raw: {},
    tags: [],
    correlationKeys: []
  },
  {
    id: 'demo-f3',
    source: 'clickup',
    entityType: 'task',
    title: 'Weekly Expense Reports',
    severity: 'low',
    health: 'Healthy',
    urgencyScore: 3,
    impactScore: 1,
    confidenceScore: 1,
    radiusScore: 10,
    category: 'tasks',
    owner: 'admin-bot',
    raw: {},
    tags: [],
    correlationKeys: []
  },
  {
    id: 'demo-f4',
    source: 'github',
    entityType: 'pr',
    title: 'Docs: Fix typo in README',
    severity: 'low',
    health: 'Healthy',
    urgencyScore: 20,
    impactScore: 1,
    confidenceScore: 1,
    radiusScore: 5,
    category: 'docs',
    raw: {},
    tags: [],
    correlationKeys: []
  },
  {
    id: 'demo-f5',
    source: 'datadog',
    entityType: 'metric',
    title: 'Daily Cost Report: AWS',
    severity: 'medium',
    health: 'Healthy',
    urgencyScore: 1,
    impactScore: 2,
    confidenceScore: 1,
    radiusScore: 25,
    category: 'business',
    raw: {},
    tags: [],
    correlationKeys: []
  },
  {
    id: 'demo-f6',
    source: 'launchdarkly',
    entityType: 'deployment',
    title: 'Stale Flag: beta-v3-ui',
    description: 'Flag has been 100% rolled out for 30 days. Needs removal.',
    severity: 'medium',
    health: 'Stale',
    urgencyScore: 30,
    impactScore: 2,
    confidenceScore: 1,
    radiusScore: 15,
    category: 'engineering',
    raw: {},
    tags: [],
    correlationKeys: []
  }
];

router.get('/demo-radius', (req, res) => {
  const items = DEMO_DATA.map(item => ({
    ...item,
    raw: sanitizeRaw(item.raw)
  }));
  res.json(correlateItems([...items]));
});

export default router;
